# Copyright 2020-2022
#
# This file is part of HiPACE++.
#
# Authors: Axel Huebl, MaxThevenet, Severin Diederichs
# License: BSD-3-Clause-LBNL

name: linux

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  linux_gcc_cxx17_omp_ompi:
    name: GNU@7.5 C++17 OMP OMPI
    runs-on: ubuntu-latest
    env: {OMP_NUM_THREADS: 2}
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: .github/workflows/setup/ubuntu_ompi.sh
    - name: CCache Cache
      uses: actions/cache@v4
      # - once stored under a key, they become immutable (even if local cache path content changes)
      # - for a refresh the key has to change, e.g., hash of a tracked file in the key
      with:
        path: |
          ~/.ccache
          ~/.cache/ccache
        key: ccache-linux-gccompompi-${{ hashFiles('.github/workflows/linux.yml') }}-${{ hashFiles('cmake/dependencies/AMReX.cmake') }}-${{ github.event.repository.pushed_at }}
        restore-keys: |
          ccache-linux-gccompompi-${{ hashFiles('.github/workflows/linux.yml') }}-
          ccache-linux-gccompompi-
    - name: Build & Install
      run: |
        cmake -S . -B build                        \
            -DHiPACE_COMPUTE=OMP                   \
            -DCMAKE_CXX_STANDARD=17                \
            -DCMAKE_INSTALL_PREFIX=/tmp/my-hipace  \
            -DCMAKE_VERBOSE_MAKEFILE=ON
        cmake --build build -j 2
    - name: Run Tests
      run: ctest --test-dir build --output-on-failure

  linux_gcc_cxx17:
    name: GNU@7.5 C++17 Serial
    runs-on: ubuntu-latest
    env: {OMP_NUM_THREADS: 2}
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: .github/workflows/setup/ubuntu.sh
    - name: CCache Cache
      uses: actions/cache@v4
      # - once stored under a key, they become immutable (even if local cache path content changes)
      # - for a refresh the key has to change, e.g., hash of a tracked file in the key
      with:
        path: |
          ~/.ccache
          ~/.cache/ccache
        key: ccache-linux-gccnompi-${{ hashFiles('.github/workflows/linux.yml') }}-${{ hashFiles('cmake/dependencies/AMReX.cmake') }}-${{ github.event.repository.pushed_at }}
        restore-keys: |
          ccache-linux-gccnompi-${{ hashFiles('.github/workflows/linux.yml') }}-
          ccache-linux-gccnompi-
    - name: Build & Install
      run: |
        cmake -S . -B build             \
            -DHiPACE_MPI=OFF            \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DHiPACE_PUSHER=AB5
        cmake --build build -j 2
    - name: Run Tests
      run: ctest --test-dir build --output-on-failure

# enable again when we open-source (free core-hours for GH Actions)
#
#  linux_clang7:
#    name: Clang@7 C++17 OMPI
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Dependencies
#      run: .github/workflows/setup/ubuntu_clang.sh
#    - name: Build & Install
#      run: |
#        mkdir build
#        cd build
#        cmake ..                                           \
#            -DCMAKE_C_COMPILER=$(which clang-7)            \
#            -DCMAKE_CXX_COMPILER=$(which clang++-7)
#        make -j 2 VERBOSE=ON
#        ctest --output-on-failure
